In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(r"../../dataset/restaurant.csv")

In [21]:
city='Noida'
price=2
rating=4.0
recommendations=df[
    (df["City"]==city)&(df["Price range"]==price)&(df["Aggregate rating"]>=rating)
]
recommendations[
    ["Restaurant Name","Aggregate rating","Votes"]
    ].head(10)

            Restaurant Name  Aggregate rating  Votes
8050   The Big Chill Cakery               4.5    147
8073              Movenpick               4.0     91
8076         The Bento Cafe               4.2    316
8100              Starbucks               4.0     59
8219  TBH ��� To Be Healthy               4.0     76
8280   The Saffron Boutique               4.0    175
8506           Wakhra Swaad               4.1    112
8602              Desi Swag               4.3     96
8616              Mr. Brown               4.0    183
8668    Salato Salad Studio               4.1     43

In [24]:
cuisines='North Indian'
recommendations=df[
    df["Cuisines"].str.contains(cuisine,case=False,na=False)
]
recommendations[
    ["Restaurant Name","City","Aggregate rating","Price range"]
].head(10)

         Restaurant Name       City  Aggregate rating  Price range
572               Gazebo  Abu Dhabi               4.0            3
579            Via Delhi  Abu Dhabi               4.0            3
580         Punjab Grill  Abu Dhabi               4.9            4
587      Barbeque Nation      Dubai               4.5            3
596            SpiceKlub      Dubai               4.4            3
603           Grub Shack      Dubai               4.3            3
604                Kamat    Sharjah               3.9            3
607     Katis Restaurant    Sharjah               4.3            3
619  Rajasthan Al Malaki    Sharjah               4.8            3
624           Jahanpanah       Agra               3.9            3

In [7]:
city = "Noida"
cuisine = "North Indian"
recommendations = df[
    (df["City"] == city) &
    (df["Aggregate rating"] >= 4.0) &
    (df["Price range"] <= 3) &
    (df["Cuisines"].str.contains(cuisine, case=False, na=False))
]
recommendations[
    [
        "Restaurant Name",
        "Cuisines",
        "Aggregate rating",
        "Votes",
        "Price range"
    ]
]

,Restaurant Name,Cuisines,Aggregate rating,Votes,Price range
8071,Made In Punjab,"North Indian, Mughlai",4.1,322,3
8074,Smaaash,"North Indian, Thai, Continental",4.0,121,3
8099,Laat Saab,"North Indian, Mughlai",4.1,111,3
8280,The Saffron Boutique,"North Indian, Chinese",4.0,175,2
8394,Barbeque Nation,"North Indian, Chinese, Mediterranean",4.3,1670,3
8506,Wakhra Swaad,"North Indian, Fast Food",4.1,112,2
8602,Desi Swag,"North Indian, Mughlai",4.3,96,2
8757,Kalpak Restaurant & Cafe,"North Indian, Chinese",4.3,150,3
9107,The Punjabiis Restro Bar,"North Indian, Chinese",4.0,395,3

In [9]:
recommendations = recommendations.sort_values(
    by=["Aggregate rating", "Votes"],
    ascending=False
)

In [10]:
def recommend(city, cuisine, price, rating):
    result = df[
        (df["City"] == city) &
        (df["Price range"] <= price) &
        (df["Aggregate rating"] >= rating) &
        (df["Cuisines"].str.contains(cuisine, case=False, na=False))
    ]
    result = result.sort_values(
        by=["Aggregate rating", "Votes"],
        ascending=False
    )
    return result[
        [
            "Restaurant Name",
            "City",
            "Cuisines",
            "Aggregate rating",
            "Votes",
            "Price range"
        ]
    ]

In [11]:
recommend(
    city="Noida",
    cuisine="North Indian",
    price=3,
    rating=4.0
)

,Restaurant Name,City,Cuisines,Aggregate rating,Votes,Price range
8394,Barbeque Nation,Noida,"North Indian, Chinese, Mediterranean",4.3,1670,3
8757,Kalpak Restaurant & Cafe,Noida,"North Indian, Chinese",4.3,150,3
8602,Desi Swag,Noida,"North Indian, Mughlai",4.3,96,2
8071,Made In Punjab,Noida,"North Indian, Mughlai",4.1,322,3
8506,Wakhra Swaad,Noida,"North Indian, Fast Food",4.1,112,2
8099,Laat Saab,Noida,"North Indian, Mughlai",4.1,111,3
9107,The Punjabiis Restro Bar,Noida,"North Indian, Chinese",4.0,395,3
8280,The Saffron Boutique,Noida,"North Indian, Chinese",4.0,175,2
8074,Smaaash,Noida,"North Indian, Thai, Continental",4.0,121,3

In [12]:
recommend(
    "Hyderabad",
    "Biryani",
    3,
    4.2
)

Empty DataFrame
Columns: [Restaurant Name, City, Cuisines, Aggregate rating, Votes, Price range]
Index: []

In [14]:
recommend(
    "Delhi",
    "Chinese",
    2,
    3.8
)

Empty DataFrame
Columns: [Restaurant Name, City, Cuisines, Aggregate rating, Votes, Price range]
Index: []

In [15]:
recommend(
    "Delhi",
    "Chinese",
    2,
    3.8
)

Empty DataFrame
Columns: [Restaurant Name, City, Cuisines, Aggregate rating, Votes, Price range]
Index: []