In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [5]:
df=pd.read_csv(r"../../dataset/restaurant_cleaned.csv")
df.isnull().sum()

Country Code            0
City                    0
Longitude               0
Latitude                0
Average Cost for two    0
                       ..
Turkish                 0
Turkish Pizza           0
Vietnamese              0
Western                 0
World Cuisine           0
Length: 264, dtype: int64

In [6]:
df=pd.get_dummies(df,columns=["City","Currency"],drop_first=True)

In [7]:
l=LabelEncoder()
df["Is delivering now"]=l.fit_transform(df["Is delivering now"])
df["Switch to order menu"]=l.fit_transform(df["Switch to order menu"])

In [18]:
df=pd.get_dummies(df,columns=["Rating color","Rating text"],drop_first=True)

In [29]:
x=df.drop("Aggregate rating",axis=1)

In [30]:
y=df["Aggregate rating"]

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=45)

In [32]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [33]:
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [39]:
rf=RandomForestRegressor(
    n_estimators=100,
    random_state=45
)
rf.fit(x_train,y_train)

RandomForestRegressor(random_state=45)

In [74]:
lr_pred=lr.predict(x_test)
lr_pred

array([3.61811292, 3.6800168 , 4.22284978, ..., 3.77055054, 3.64290378,
       3.0520269 ], shape=(1911,))

In [41]:
dt_pred=dt.predict(x_test)
print(dt_pred)

[3.7 3.9 4.3 ... 3.6 3.5 3. ]

In [42]:
rf_pred=rf.predict(x_test)
print(rf_pred)

[3.639 3.623 4.162 ... 3.773 3.618 3.098]

In [43]:
lr_mae=mean_absolute_error(y_test,lr_pred)
dt_mae=mean_absolute_error(y_test,dt_pred)
rf_mae=mean_absolute_error(y_test,rf_pred)

In [44]:
lr_mse=mean_squared_error(y_test,lr_pred)
dt_mse=mean_squared_error(y_test,dt_pred)
rf_mse=mean_squared_error(y_test,rf_pred)

In [45]:
lr_rmse=np.sqrt(mean_squared_error(y_test,lr_pred))
dt_rmse=np.sqrt(mean_squared_error(y_test,dt_pred))
rf_rmse=np.sqrt(mean_squared_error(y_test,rf_pred))

In [46]:
lr_r2=r2_score(y_test,lr_pred)
dt_r2=r2_score(y_test,dt_pred)
rf_r2=r2_score(y_test,rf_pred)

In [47]:
print("Random Forest")
print("MAE :", rf_mae)
print("MSE :", rf_mse)
print("RMSE:", rf_rmse)
print("R2 Score:", rf_r2)

Random Forest
MAE : 0.12235007849293565
MSE : 0.031838262166405014
RMSE: 0.17843279453734118
R2 Score: 0.985829206845484

In [48]:
print("Decision Tree")
print("MAE :", dt_mae)
print("MSE :", dt_mse)
print("RMSE:", dt_rmse)
print("R2 Score:", dt_r2)

Decision Tree
MAE : 0.15311355311355312
MSE : 0.05900575614861328
RMSE: 0.24291100458524575
R2 Score: 0.9737373113853526

In [49]:
print("Linear Regression")
print("MAE :", lr_mae)
print("MSE :", lr_mse)
print("RMSE:", lr_rmse)
print("R2 Score:", lr_r2)

Linear Regression
MAE : 0.1350794560267235
MSE : 0.03343184091913446
RMSE: 0.18284376095217048
R2 Score: 0.985119925831265

In [93]:
comparsion1=pd.DataFrame({
    "models":["Linear Regression","Decision Tree","Random Forest"],
    "MAE":[lr_mae,dt_mae,rf_mae],
    "MSE":[lr_mse,dt_mse,rf_mse],
    "RMSE":[lr_rmse,dt_rmse,rf_rmse],
    "r2_score":[lr_r2,dt_r2,rf_r2]
})
comparsion1

              models       MAE       MSE      RMSE  r2_score
0  Linear Regression  0.135079  0.033432  0.182844  0.985120
1      Decision Tree  0.153114  0.059006  0.242911  0.973737
2      Random Forest  0.122350  0.031838  0.178433  0.985829

In [94]:
best=comparsion.sort_values(by="r2_score",ascending=False)
best

              models       MAE       MSE      RMSE  r2_score
2      Random Forest  0.122350  0.031838  0.178433  0.985829
0  Linear Regression  0.135079  0.033432  0.182844  0.985120
1      Decision Tree  0.153114  0.059006  0.242911  0.973737

In [95]:
best=comparsion.sort_values(by="MAE",ascending=False)
best

              models       MAE       MSE      RMSE  r2_score
1      Decision Tree  0.153114  0.059006  0.242911  0.973737
0  Linear Regression  0.135079  0.033432  0.182844  0.985120
2      Random Forest  0.122350  0.031838  0.178433  0.985829

In [96]:
best=comparsion.sort_values(by="MSE",ascending=False)
best

              models       MAE       MSE      RMSE  r2_score
1      Decision Tree  0.153114  0.059006  0.242911  0.973737
0  Linear Regression  0.135079  0.033432  0.182844  0.985120
2      Random Forest  0.122350  0.031838  0.178433  0.985829

In [97]:
best=comparsion.sort_values(by="RMSE",ascending=False)
best

              models       MAE       MSE      RMSE  r2_score
1      Decision Tree  0.153114  0.059006  0.242911  0.973737
0  Linear Regression  0.135079  0.033432  0.182844  0.985120
2      Random Forest  0.122350  0.031838  0.178433  0.985829

In [99]:
print(comparison.columns)

Index(['Actual Rating', 'Predicted Rating'], dtype='object')